# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c961e9b313a907bd8375ac70692ebd41b8f2b2e0f719ca3c951541c05462467ff110dee02364a83ce52d025a5489ad7cd5d1336b056cd08617f42a89222c6ab8

test:
  secret_key_base: 7be2bacb7b50f11471e7f6af52fbf879fecc7c4d5b1e71f1a6156843038f3e7ab926c37a82aa801f1606736bf96a06d61aebbfd9832ffc1a213631947bf2f925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
